/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PropostasRouteImport } from './routes/propostas'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FunilRouteImport } from './routes/funil'
import { Route as EmailsRouteImport } from './routes/emails'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminBillingRouteImport } from './routes/admin/billing'
import { Route as TTenantSlugRouteRouteImport } from './routes/t/$tenantSlug/route'
import { Route as AdminTenantsIndexRouteImport } from './routes/admin/tenants/index'
import { Route as AdminTenantsTenantIdRouteImport } from './routes/admin/tenants/$tenantId'
import { Route as TTenantSlugPortalRouteRouteImport } from './routes/t/$tenantSlug/portal/route'
import { Route as TTenantSlugAppRouteRouteImport } from './routes/t/$tenantSlug/app/route'
import { Route as TTenantSlugPortalIndexRouteImport } from './routes/t/$tenantSlug/portal/index'
import { Route as TTenantSlugAppIndexRouteImport } from './routes/t/$tenantSlug/app/index'
import { Route as TTenantSlugPortalPropostasRouteImport } from './routes/t/$tenantSlug/portal/propostas'
import { Route as TTenantSlugPortalProjetosRouteImport } from './routes/t/$tenantSlug/portal/projetos'
import { Route as TTenantSlugPortalFaturamentoRouteImport } from './routes/t/$tenantSlug/portal/faturamento'
import { Route as TTenantSlugPortalChamadosRouteImport } from './routes/t/$tenantSlug/portal/chamados'
import { Route as TTenantSlugAppPropostasRouteImport } from './routes/t/$tenantSlug/app/propostas'
import { Route as TTenantSlugAppPainelRouteImport } from './routes/t/$tenantSlug/app/painel'
import { Route as TTenantSlugAppFaturamentoRouteImport } from './routes/t/$tenantSlug/app/faturamento'
import { Route as TTenantSlugAppEmailsRouteImport } from './routes/t/$tenantSlug/app/emails'
import { Route as TTenantSlugAppConfiguracoesRouteImport } from './routes/t/$tenantSlug/app/configuracoes'
import { Route as TTenantSlugAppComunicacaoRouteImport } from './routes/t/$tenantSlug/app/comunicacao'
import { Route as TTenantSlugAppChatsRouteImport } from './routes/t/$tenantSlug/app/chats'
import { Route as TTenantSlugAppChamadosRouteImport } from './routes/t/$tenantSlug/app/chamados'
import { Route as TTenantSlugAppAgendaRouteImport } from './routes/t/$tenantSlug/app/agenda'
import { Route as TTenantSlugAppCreatorRouteRouteImport } from './routes/t/$tenantSlug/app/creator/route'
import { Route as TTenantSlugAppCommunicationsRouteRouteImport } from './routes/t/$tenantSlug/app/communications/route'
import { Route as TTenantSlugAppFunilIndexRouteImport } from './routes/t/$tenantSlug/app/funil/index'
import { Route as TTenantSlugAppCreatorIndexRouteImport } from './routes/t/$tenantSlug/app/creator/index'
import { Route as TTenantSlugAppCommunicationsIndexRouteImport } from './routes/t/$tenantSlug/app/communications/index'
import { Route as TTenantSlugAppFunilPipelineIdRouteImport } from './routes/t/$tenantSlug/app/funil/$pipelineId'
import { Route as TTenantSlugAppCreatorSponsorsRouteImport } from './routes/t/$tenantSlug/app/creator/sponsors'
import { Route as TTenantSlugAppCreatorCampaignsRouteImport } from './routes/t/$tenantSlug/app/creator/campaigns'
import { Route as TTenantSlugAppCreatorBrandsRouteImport } from './routes/t/$tenantSlug/app/creator/brands'
import { Route as TTenantSlugAppCreatorAgenciesRouteImport } from './routes/t/$tenantSlug/app/creator/agencies'
import { Route as TTenantSlugAppCommunicationsTicketsRouteImport } from './routes/t/$tenantSlug/app/communications/tickets'
import { Route as TTenantSlugAppCommunicationsSettingsRouteImport } from './routes/t/$tenantSlug/app/communications/settings'
import { Route as TTenantSlugAppCommunicationsReportsRouteImport } from './routes/t/$tenantSlug/app/communications/reports'
import { Route as TTenantSlugAppCommunicationsIntegrationsRouteImport } from './routes/t/$tenantSlug/app/communications/integrations'
import { Route as TTenantSlugAppCommunicationsInboxRouteImport } from './routes/t/$tenantSlug/app/communications/inbox'
import { Route as TTenantSlugAppCommunicationsChannelsRouteImport } from './routes/t/$tenantSlug/app/communications/channels'

const PropostasRoute = PropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FunilRoute = FunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsRoute = EmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRouteRoute,
} as any)
const TTenantSlugRouteRoute = TTenantSlugRouteRouteImport.update({
  id: '/t/$tenantSlug',
  path: '/t/$tenantSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTenantsIndexRoute = AdminTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTenantsTenantIdRoute = AdminTenantsTenantIdRouteImport.update({
  id: '/tenants/$tenantId',
  path: '/tenants/$tenantId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const TTenantSlugPortalRouteRoute = TTenantSlugPortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => TTenantSlugRouteRoute,
} as any)
const TTenantSlugAppRouteRoute = TTenantSlugAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => TTenantSlugRouteRoute,
} as any)
const TTenantSlugPortalIndexRoute = TTenantSlugPortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TTenantSlugPortalRouteRoute,
} as any)
const TTenantSlugAppIndexRoute = TTenantSlugAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TTenantSlugAppRouteRoute,
} as any)
const TTenantSlugPortalPropostasRoute =
  TTenantSlugPortalPropostasRouteImport.update({
    id: '/propostas',
    path: '/propostas',
    getParentRoute: () => TTenantSlugPortalRouteRoute,
  } as any)
const TTenantSlugPortalProjetosRoute =
  TTenantSlugPortalProjetosRouteImport.update({
    id: '/projetos',
    path: '/projetos',
    getParentRoute: () => TTenantSlugPortalRouteRoute,
  } as any)
const TTenantSlugPortalFaturamentoRoute =
  TTenantSlugPortalFaturamentoRouteImport.update({
    id: '/faturamento',
    path: '/faturamento',
    getParentRoute: () => TTenantSlugPortalRouteRoute,
  } as any)
const TTenantSlugPortalChamadosRoute =
  TTenantSlugPortalChamadosRouteImport.update({
    id: '/chamados',
    path: '/chamados',
    getParentRoute: () => TTenantSlugPortalRouteRoute,
  } as any)
const TTenantSlugAppPropostasRoute = TTenantSlugAppPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => TTenantSlugAppRouteRoute,
} as any)
const TTenantSlugAppPainelRoute = TTenantSlugAppPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => TTenantSlugAppRouteRoute,
} as any)
const TTenantSlugAppFaturamentoRoute =
  TTenantSlugAppFaturamentoRouteImport.update({
    id: '/faturamento',
    path: '/faturamento',
    getParentRoute: () => TTenantSlugAppRouteRoute,
  } as any)
const TTenantSlugAppEmailsRoute = TTenantSlugAppEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => TTenantSlugAppRouteRoute,
} as any)
const TTenantSlugAppConfiguracoesRoute =
  TTenantSlugAppConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => TTenantSlugAppRouteRoute,
  } as any)
const TTenantSlugAppComunicacaoRoute =
  TTenantSlugAppComunicacaoRouteImport.update({
    id: '/comunicacao',
    path: '/comunicacao',
    getParentRoute: () => TTenantSlugAppRouteRoute,
  } as any)
const TTenantSlugAppChatsRoute = TTenantSlugAppChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => TTenantSlugAppRouteRoute,
} as any)
const TTenantSlugAppChamadosRoute = TTenantSlugAppChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => TTenantSlugAppRouteRoute,
} as any)
const TTenantSlugAppAgendaRoute = TTenantSlugAppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => TTenantSlugAppRouteRoute,
} as any)
const TTenantSlugAppCreatorRouteRoute =
  TTenantSlugAppCreatorRouteRouteImport.update({
    id: '/creator',
    path: '/creator',
    getParentRoute: () => TTenantSlugAppRouteRoute,
  } as any)
const TTenantSlugAppCommunicationsRouteRoute =
  TTenantSlugAppCommunicationsRouteRouteImport.update({
    id: '/communications',
    path: '/communications',
    getParentRoute: () => TTenantSlugAppRouteRoute,
  } as any)
const TTenantSlugAppFunilIndexRoute =
  TTenantSlugAppFunilIndexRouteImport.update({
    id: '/funil/',
    path: '/funil/',
    getParentRoute: () => TTenantSlugAppRouteRoute,
  } as any)
const TTenantSlugAppCreatorIndexRoute =
  TTenantSlugAppCreatorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TTenantSlugAppCreatorRouteRoute,
  } as any)
const TTenantSlugAppCommunicationsIndexRoute =
  TTenantSlugAppCommunicationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TTenantSlugAppCommunicationsRouteRoute,
  } as any)
const TTenantSlugAppFunilPipelineIdRoute =
  TTenantSlugAppFunilPipelineIdRouteImport.update({
    id: '/funil/$pipelineId',
    path: '/funil/$pipelineId',
    getParentRoute: () => TTenantSlugAppRouteRoute,
  } as any)
const TTenantSlugAppCreatorSponsorsRoute =
  TTenantSlugAppCreatorSponsorsRouteImport.update({
    id: '/sponsors',
    path: '/sponsors',
    getParentRoute: () => TTenantSlugAppCreatorRouteRoute,
  } as any)
const TTenantSlugAppCreatorCampaignsRoute =
  TTenantSlugAppCreatorCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => TTenantSlugAppCreatorRouteRoute,
  } as any)
const TTenantSlugAppCreatorBrandsRoute =
  TTenantSlugAppCreatorBrandsRouteImport.update({
    id: '/brands',
    path: '/brands',
    getParentRoute: () => TTenantSlugAppCreatorRouteRoute,
  } as any)
const TTenantSlugAppCreatorAgenciesRoute =
  TTenantSlugAppCreatorAgenciesRouteImport.update({
    id: '/agencies',
    path: '/agencies',
    getParentRoute: () => TTenantSlugAppCreatorRouteRoute,
  } as any)
const TTenantSlugAppCommunicationsTicketsRoute =
  TTenantSlugAppCommunicationsTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => TTenantSlugAppCommunicationsRouteRoute,
  } as any)
const TTenantSlugAppCommunicationsSettingsRoute =
  TTenantSlugAppCommunicationsSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => TTenantSlugAppCommunicationsRouteRoute,
  } as any)
const TTenantSlugAppCommunicationsReportsRoute =
  TTenantSlugAppCommunicationsReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => TTenantSlugAppCommunicationsRouteRoute,
  } as any)
const TTenantSlugAppCommunicationsIntegrationsRoute =
  TTenantSlugAppCommunicationsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => TTenantSlugAppCommunicationsRouteRoute,
  } as any)
const TTenantSlugAppCommunicationsInboxRoute =
  TTenantSlugAppCommunicationsInboxRouteImport.update({
    id: '/inbox',
    path: '/inbox',
    getParentRoute: () => TTenantSlugAppCommunicationsRouteRoute,
  } as any)
const TTenantSlugAppCommunicationsChannelsRoute =
  TTenantSlugAppCommunicationsChannelsRouteImport.update({
    id: '/channels',
    path: '/channels',
    getParentRoute: () => TTenantSlugAppCommunicationsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/chats': typeof ChatsRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/emails': typeof EmailsRoute
  '/funil': typeof FunilRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/propostas': typeof PropostasRoute
  '/t/$tenantSlug': typeof TTenantSlugRouteRouteWithChildren
  '/admin/billing': typeof AdminBillingRoute
  '/admin/': typeof AdminIndexRoute
  '/t/$tenantSlug/app': typeof TTenantSlugAppRouteRouteWithChildren
  '/t/$tenantSlug/portal': typeof TTenantSlugPortalRouteRouteWithChildren
  '/admin/tenants/$tenantId': typeof AdminTenantsTenantIdRoute
  '/admin/tenants/': typeof AdminTenantsIndexRoute
  '/t/$tenantSlug/app/communications': typeof TTenantSlugAppCommunicationsRouteRouteWithChildren
  '/t/$tenantSlug/app/creator': typeof TTenantSlugAppCreatorRouteRouteWithChildren
  '/t/$tenantSlug/app/agenda': typeof TTenantSlugAppAgendaRoute
  '/t/$tenantSlug/app/chamados': typeof TTenantSlugAppChamadosRoute
  '/t/$tenantSlug/app/chats': typeof TTenantSlugAppChatsRoute
  '/t/$tenantSlug/app/comunicacao': typeof TTenantSlugAppComunicacaoRoute
  '/t/$tenantSlug/app/configuracoes': typeof TTenantSlugAppConfiguracoesRoute
  '/t/$tenantSlug/app/emails': typeof TTenantSlugAppEmailsRoute
  '/t/$tenantSlug/app/faturamento': typeof TTenantSlugAppFaturamentoRoute
  '/t/$tenantSlug/app/painel': typeof TTenantSlugAppPainelRoute
  '/t/$tenantSlug/app/propostas': typeof TTenantSlugAppPropostasRoute
  '/t/$tenantSlug/portal/chamados': typeof TTenantSlugPortalChamadosRoute
  '/t/$tenantSlug/portal/faturamento': typeof TTenantSlugPortalFaturamentoRoute
  '/t/$tenantSlug/portal/projetos': typeof TTenantSlugPortalProjetosRoute
  '/t/$tenantSlug/portal/propostas': typeof TTenantSlugPortalPropostasRoute
  '/t/$tenantSlug/app/': typeof TTenantSlugAppIndexRoute
  '/t/$tenantSlug/portal/': typeof TTenantSlugPortalIndexRoute
  '/t/$tenantSlug/app/communications/channels': typeof TTenantSlugAppCommunicationsChannelsRoute
  '/t/$tenantSlug/app/communications/inbox': typeof TTenantSlugAppCommunicationsInboxRoute
  '/t/$tenantSlug/app/communications/integrations': typeof TTenantSlugAppCommunicationsIntegrationsRoute
  '/t/$tenantSlug/app/communications/reports': typeof TTenantSlugAppCommunicationsReportsRoute
  '/t/$tenantSlug/app/communications/settings': typeof TTenantSlugAppCommunicationsSettingsRoute
  '/t/$tenantSlug/app/communications/tickets': typeof TTenantSlugAppCommunicationsTicketsRoute
  '/t/$tenantSlug/app/creator/agencies': typeof TTenantSlugAppCreatorAgenciesRoute
  '/t/$tenantSlug/app/creator/brands': typeof TTenantSlugAppCreatorBrandsRoute
  '/t/$tenantSlug/app/creator/campaigns': typeof TTenantSlugAppCreatorCampaignsRoute
  '/t/$tenantSlug/app/creator/sponsors': typeof TTenantSlugAppCreatorSponsorsRoute
  '/t/$tenantSlug/app/funil/$pipelineId': typeof TTenantSlugAppFunilPipelineIdRoute
  '/t/$tenantSlug/app/communications/': typeof TTenantSlugAppCommunicationsIndexRoute
  '/t/$tenantSlug/app/creator/': typeof TTenantSlugAppCreatorIndexRoute
  '/t/$tenantSlug/app/funil/': typeof TTenantSlugAppFunilIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/chats': typeof ChatsRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/emails': typeof EmailsRoute
  '/funil': typeof FunilRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/propostas': typeof PropostasRoute
  '/t/$tenantSlug': typeof TTenantSlugRouteRouteWithChildren
  '/admin/billing': typeof AdminBillingRoute
  '/admin': typeof AdminIndexRoute
  '/admin/tenants/$tenantId': typeof AdminTenantsTenantIdRoute
  '/admin/tenants': typeof AdminTenantsIndexRoute
  '/t/$tenantSlug/app/agenda': typeof TTenantSlugAppAgendaRoute
  '/t/$tenantSlug/app/chamados': typeof TTenantSlugAppChamadosRoute
  '/t/$tenantSlug/app/chats': typeof TTenantSlugAppChatsRoute
  '/t/$tenantSlug/app/comunicacao': typeof TTenantSlugAppComunicacaoRoute
  '/t/$tenantSlug/app/configuracoes': typeof TTenantSlugAppConfiguracoesRoute
  '/t/$tenantSlug/app/emails': typeof TTenantSlugAppEmailsRoute
  '/t/$tenantSlug/app/faturamento': typeof TTenantSlugAppFaturamentoRoute
  '/t/$tenantSlug/app/painel': typeof TTenantSlugAppPainelRoute
  '/t/$tenantSlug/app/propostas': typeof TTenantSlugAppPropostasRoute
  '/t/$tenantSlug/portal/chamados': typeof TTenantSlugPortalChamadosRoute
  '/t/$tenantSlug/portal/faturamento': typeof TTenantSlugPortalFaturamentoRoute
  '/t/$tenantSlug/portal/projetos': typeof TTenantSlugPortalProjetosRoute
  '/t/$tenantSlug/portal/propostas': typeof TTenantSlugPortalPropostasRoute
  '/t/$tenantSlug/app': typeof TTenantSlugAppIndexRoute
  '/t/$tenantSlug/portal': typeof TTenantSlugPortalIndexRoute
  '/t/$tenantSlug/app/communications/channels': typeof TTenantSlugAppCommunicationsChannelsRoute
  '/t/$tenantSlug/app/communications/inbox': typeof TTenantSlugAppCommunicationsInboxRoute
  '/t/$tenantSlug/app/communications/integrations': typeof TTenantSlugAppCommunicationsIntegrationsRoute
  '/t/$tenantSlug/app/communications/reports': typeof TTenantSlugAppCommunicationsReportsRoute
  '/t/$tenantSlug/app/communications/settings': typeof TTenantSlugAppCommunicationsSettingsRoute
  '/t/$tenantSlug/app/communications/tickets': typeof TTenantSlugAppCommunicationsTicketsRoute
  '/t/$tenantSlug/app/creator/agencies': typeof TTenantSlugAppCreatorAgenciesRoute
  '/t/$tenantSlug/app/creator/brands': typeof TTenantSlugAppCreatorBrandsRoute
  '/t/$tenantSlug/app/creator/campaigns': typeof TTenantSlugAppCreatorCampaignsRoute
  '/t/$tenantSlug/app/creator/sponsors': typeof TTenantSlugAppCreatorSponsorsRoute
  '/t/$tenantSlug/app/funil/$pipelineId': typeof TTenantSlugAppFunilPipelineIdRoute
  '/t/$tenantSlug/app/communications': typeof TTenantSlugAppCommunicationsIndexRoute
  '/t/$tenantSlug/app/creator': typeof TTenantSlugAppCreatorIndexRoute
  '/t/$tenantSlug/app/funil': typeof TTenantSlugAppFunilIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/chats': typeof ChatsRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/emails': typeof EmailsRoute
  '/funil': typeof FunilRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/propostas': typeof PropostasRoute
  '/t/$tenantSlug': typeof TTenantSlugRouteRouteWithChildren
  '/admin/billing': typeof AdminBillingRoute
  '/admin/': typeof AdminIndexRoute
  '/t/$tenantSlug/app': typeof TTenantSlugAppRouteRouteWithChildren
  '/t/$tenantSlug/portal': typeof TTenantSlugPortalRouteRouteWithChildren
  '/admin/tenants/$tenantId': typeof AdminTenantsTenantIdRoute
  '/admin/tenants/': typeof AdminTenantsIndexRoute
  '/t/$tenantSlug/app/communications': typeof TTenantSlugAppCommunicationsRouteRouteWithChildren
  '/t/$tenantSlug/app/creator': typeof TTenantSlugAppCreatorRouteRouteWithChildren
  '/t/$tenantSlug/app/agenda': typeof TTenantSlugAppAgendaRoute
  '/t/$tenantSlug/app/chamados': typeof TTenantSlugAppChamadosRoute
  '/t/$tenantSlug/app/chats': typeof TTenantSlugAppChatsRoute
  '/t/$tenantSlug/app/comunicacao': typeof TTenantSlugAppComunicacaoRoute
  '/t/$tenantSlug/app/configuracoes': typeof TTenantSlugAppConfiguracoesRoute
  '/t/$tenantSlug/app/emails': typeof TTenantSlugAppEmailsRoute
  '/t/$tenantSlug/app/faturamento': typeof TTenantSlugAppFaturamentoRoute
  '/t/$tenantSlug/app/painel': typeof TTenantSlugAppPainelRoute
  '/t/$tenantSlug/app/propostas': typeof TTenantSlugAppPropostasRoute
  '/t/$tenantSlug/portal/chamados': typeof TTenantSlugPortalChamadosRoute
  '/t/$tenantSlug/portal/faturamento': typeof TTenantSlugPortalFaturamentoRoute
  '/t/$tenantSlug/portal/projetos': typeof TTenantSlugPortalProjetosRoute
  '/t/$tenantSlug/portal/propostas': typeof TTenantSlugPortalPropostasRoute
  '/t/$tenantSlug/app/': typeof TTenantSlugAppIndexRoute
  '/t/$tenantSlug/portal/': typeof TTenantSlugPortalIndexRoute
  '/t/$tenantSlug/app/communications/channels': typeof TTenantSlugAppCommunicationsChannelsRoute
  '/t/$tenantSlug/app/communications/inbox': typeof TTenantSlugAppCommunicationsInboxRoute
  '/t/$tenantSlug/app/communications/integrations': typeof TTenantSlugAppCommunicationsIntegrationsRoute
  '/t/$tenantSlug/app/communications/reports': typeof TTenantSlugAppCommunicationsReportsRoute
  '/t/$tenantSlug/app/communications/settings': typeof TTenantSlugAppCommunicationsSettingsRoute
  '/t/$tenantSlug/app/communications/tickets': typeof TTenantSlugAppCommunicationsTicketsRoute
  '/t/$tenantSlug/app/creator/agencies': typeof TTenantSlugAppCreatorAgenciesRoute
  '/t/$tenantSlug/app/creator/brands': typeof TTenantSlugAppCreatorBrandsRoute
  '/t/$tenantSlug/app/creator/campaigns': typeof TTenantSlugAppCreatorCampaignsRoute
  '/t/$tenantSlug/app/creator/sponsors': typeof TTenantSlugAppCreatorSponsorsRoute
  '/t/$tenantSlug/app/funil/$pipelineId': typeof TTenantSlugAppFunilPipelineIdRoute
  '/t/$tenantSlug/app/communications/': typeof TTenantSlugAppCommunicationsIndexRoute
  '/t/$tenantSlug/app/creator/': typeof TTenantSlugAppCreatorIndexRoute
  '/t/$tenantSlug/app/funil/': typeof TTenantSlugAppFunilIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agenda'
    | '/chats'
    | '/configuracoes'
    | '/emails'
    | '/funil'
    | '/login'
    | '/painel'
    | '/propostas'
    | '/t/$tenantSlug'
    | '/admin/billing'
    | '/admin/'
    | '/t/$tenantSlug/app'
    | '/t/$tenantSlug/portal'
    | '/admin/tenants/$tenantId'
    | '/admin/tenants/'
    | '/t/$tenantSlug/app/communications'
    | '/t/$tenantSlug/app/creator'
    | '/t/$tenantSlug/app/agenda'
    | '/t/$tenantSlug/app/chamados'
    | '/t/$tenantSlug/app/chats'
    | '/t/$tenantSlug/app/comunicacao'
    | '/t/$tenantSlug/app/configuracoes'
    | '/t/$tenantSlug/app/emails'
    | '/t/$tenantSlug/app/faturamento'
    | '/t/$tenantSlug/app/painel'
    | '/t/$tenantSlug/app/propostas'
    | '/t/$tenantSlug/portal/chamados'
    | '/t/$tenantSlug/portal/faturamento'
    | '/t/$tenantSlug/portal/projetos'
    | '/t/$tenantSlug/portal/propostas'
    | '/t/$tenantSlug/app/'
    | '/t/$tenantSlug/portal/'
    | '/t/$tenantSlug/app/communications/channels'
    | '/t/$tenantSlug/app/communications/inbox'
    | '/t/$tenantSlug/app/communications/integrations'
    | '/t/$tenantSlug/app/communications/reports'
    | '/t/$tenantSlug/app/communications/settings'
    | '/t/$tenantSlug/app/communications/tickets'
    | '/t/$tenantSlug/app/creator/agencies'
    | '/t/$tenantSlug/app/creator/brands'
    | '/t/$tenantSlug/app/creator/campaigns'
    | '/t/$tenantSlug/app/creator/sponsors'
    | '/t/$tenantSlug/app/funil/$pipelineId'
    | '/t/$tenantSlug/app/communications/'
    | '/t/$tenantSlug/app/creator/'
    | '/t/$tenantSlug/app/funil/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/chats'
    | '/configuracoes'
    | '/emails'
    | '/funil'
    | '/login'
    | '/painel'
    | '/propostas'
    | '/t/$tenantSlug'
    | '/admin/billing'
    | '/admin'
    | '/admin/tenants/$tenantId'
    | '/admin/tenants'
    | '/t/$tenantSlug/app/agenda'
    | '/t/$tenantSlug/app/chamados'
    | '/t/$tenantSlug/app/chats'
    | '/t/$tenantSlug/app/comunicacao'
    | '/t/$tenantSlug/app/configuracoes'
    | '/t/$tenantSlug/app/emails'
    | '/t/$tenantSlug/app/faturamento'
    | '/t/$tenantSlug/app/painel'
    | '/t/$tenantSlug/app/propostas'
    | '/t/$tenantSlug/portal/chamados'
    | '/t/$tenantSlug/portal/faturamento'
    | '/t/$tenantSlug/portal/projetos'
    | '/t/$tenantSlug/portal/propostas'
    | '/t/$tenantSlug/app'
    | '/t/$tenantSlug/portal'
    | '/t/$tenantSlug/app/communications/channels'
    | '/t/$tenantSlug/app/communications/inbox'
    | '/t/$tenantSlug/app/communications/integrations'
    | '/t/$tenantSlug/app/communications/reports'
    | '/t/$tenantSlug/app/communications/settings'
    | '/t/$tenantSlug/app/communications/tickets'
    | '/t/$tenantSlug/app/creator/agencies'
    | '/t/$tenantSlug/app/creator/brands'
    | '/t/$tenantSlug/app/creator/campaigns'
    | '/t/$tenantSlug/app/creator/sponsors'
    | '/t/$tenantSlug/app/funil/$pipelineId'
    | '/t/$tenantSlug/app/communications'
    | '/t/$tenantSlug/app/creator'
    | '/t/$tenantSlug/app/funil'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agenda'
    | '/chats'
    | '/configuracoes'
    | '/emails'
    | '/funil'
    | '/login'
    | '/painel'
    | '/propostas'
    | '/t/$tenantSlug'
    | '/admin/billing'
    | '/admin/'
    | '/t/$tenantSlug/app'
    | '/t/$tenantSlug/portal'
    | '/admin/tenants/$tenantId'
    | '/admin/tenants/'
    | '/t/$tenantSlug/app/communications'
    | '/t/$tenantSlug/app/creator'
    | '/t/$tenantSlug/app/agenda'
    | '/t/$tenantSlug/app/chamados'
    | '/t/$tenantSlug/app/chats'
    | '/t/$tenantSlug/app/comunicacao'
    | '/t/$tenantSlug/app/configuracoes'
    | '/t/$tenantSlug/app/emails'
    | '/t/$tenantSlug/app/faturamento'
    | '/t/$tenantSlug/app/painel'
    | '/t/$tenantSlug/app/propostas'
    | '/t/$tenantSlug/portal/chamados'
    | '/t/$tenantSlug/portal/faturamento'
    | '/t/$tenantSlug/portal/projetos'
    | '/t/$tenantSlug/portal/propostas'
    | '/t/$tenantSlug/app/'
    | '/t/$tenantSlug/portal/'
    | '/t/$tenantSlug/app/communications/channels'
    | '/t/$tenantSlug/app/communications/inbox'
    | '/t/$tenantSlug/app/communications/integrations'
    | '/t/$tenantSlug/app/communications/reports'
    | '/t/$tenantSlug/app/communications/settings'
    | '/t/$tenantSlug/app/communications/tickets'
    | '/t/$tenantSlug/app/creator/agencies'
    | '/t/$tenantSlug/app/creator/brands'
    | '/t/$tenantSlug/app/creator/campaigns'
    | '/t/$tenantSlug/app/creator/sponsors'
    | '/t/$tenantSlug/app/funil/$pipelineId'
    | '/t/$tenantSlug/app/communications/'
    | '/t/$tenantSlug/app/creator/'
    | '/t/$tenantSlug/app/funil/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AgendaRoute: typeof AgendaRoute
  ChatsRoute: typeof ChatsRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EmailsRoute: typeof EmailsRoute
  FunilRoute: typeof FunilRoute
  LoginRoute: typeof LoginRoute
  PainelRoute: typeof PainelRoute
  PropostasRoute: typeof PropostasRoute
  TTenantSlugRouteRoute: typeof TTenantSlugRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/propostas': {
      id: '/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof PropostasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funil': {
      id: '/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof FunilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails': {
      id: '/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof EmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/t/$tenantSlug': {
      id: '/t/$tenantSlug'
      path: '/t/$tenantSlug'
      fullPath: '/t/$tenantSlug'
      preLoaderRoute: typeof TTenantSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenants/': {
      id: '/admin/tenants/'
      path: '/tenants'
      fullPath: '/admin/tenants/'
      preLoaderRoute: typeof AdminTenantsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tenants/$tenantId': {
      id: '/admin/tenants/$tenantId'
      path: '/tenants/$tenantId'
      fullPath: '/admin/tenants/$tenantId'
      preLoaderRoute: typeof AdminTenantsTenantIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/t/$tenantSlug/portal': {
      id: '/t/$tenantSlug/portal'
      path: '/portal'
      fullPath: '/t/$tenantSlug/portal'
      preLoaderRoute: typeof TTenantSlugPortalRouteRouteImport
      parentRoute: typeof TTenantSlugRouteRoute
    }
    '/t/$tenantSlug/app': {
      id: '/t/$tenantSlug/app'
      path: '/app'
      fullPath: '/t/$tenantSlug/app'
      preLoaderRoute: typeof TTenantSlugAppRouteRouteImport
      parentRoute: typeof TTenantSlugRouteRoute
    }
    '/t/$tenantSlug/portal/': {
      id: '/t/$tenantSlug/portal/'
      path: '/'
      fullPath: '/t/$tenantSlug/portal/'
      preLoaderRoute: typeof TTenantSlugPortalIndexRouteImport
      parentRoute: typeof TTenantSlugPortalRouteRoute
    }
    '/t/$tenantSlug/app/': {
      id: '/t/$tenantSlug/app/'
      path: '/'
      fullPath: '/t/$tenantSlug/app/'
      preLoaderRoute: typeof TTenantSlugAppIndexRouteImport
      parentRoute: typeof TTenantSlugAppRouteRoute
    }
    '/t/$tenantSlug/portal/propostas': {
      id: '/t/$tenantSlug/portal/propostas'
      path: '/propostas'
      fullPath: '/t/$tenantSlug/portal/propostas'
      preLoaderRoute: typeof TTenantSlugPortalPropostasRouteImport
      parentRoute: typeof TTenantSlugPortalRouteRoute
    }
    '/t/$tenantSlug/portal/projetos': {
      id: '/t/$tenantSlug/portal/projetos'
      path: '/projetos'
      fullPath: '/t/$tenantSlug/portal/projetos'
      preLoaderRoute: typeof TTenantSlugPortalProjetosRouteImport
      parentRoute: typeof TTenantSlugPortalRouteRoute
    }
    '/t/$tenantSlug/portal/faturamento': {
      id: '/t/$tenantSlug/portal/faturamento'
      path: '/faturamento'
      fullPath: '/t/$tenantSlug/portal/faturamento'
      preLoaderRoute: typeof TTenantSlugPortalFaturamentoRouteImport
      parentRoute: typeof TTenantSlugPortalRouteRoute
    }
    '/t/$tenantSlug/portal/chamados': {
      id: '/t/$tenantSlug/portal/chamados'
      path: '/chamados'
      fullPath: '/t/$tenantSlug/portal/chamados'
      preLoaderRoute: typeof TTenantSlugPortalChamadosRouteImport
      parentRoute: typeof TTenantSlugPortalRouteRoute
    }
    '/t/$tenantSlug/app/propostas': {
      id: '/t/$tenantSlug/app/propostas'
      path: '/propostas'
      fullPath: '/t/$tenantSlug/app/propostas'
      preLoaderRoute: typeof TTenantSlugAppPropostasRouteImport
      parentRoute: typeof TTenantSlugAppRouteRoute
    }
    '/t/$tenantSlug/app/painel': {
      id: '/t/$tenantSlug/app/painel'
      path: '/painel'
      fullPath: '/t/$tenantSlug/app/painel'
      preLoaderRoute: typeof TTenantSlugAppPainelRouteImport
      parentRoute: typeof TTenantSlugAppRouteRoute
    }
    '/t/$tenantSlug/app/faturamento': {
      id: '/t/$tenantSlug/app/faturamento'
      path: '/faturamento'
      fullPath: '/t/$tenantSlug/app/faturamento'
      preLoaderRoute: typeof TTenantSlugAppFaturamentoRouteImport
      parentRoute: typeof TTenantSlugAppRouteRoute
    }
    '/t/$tenantSlug/app/emails': {
      id: '/t/$tenantSlug/app/emails'
      path: '/emails'
      fullPath: '/t/$tenantSlug/app/emails'
      preLoaderRoute: typeof TTenantSlugAppEmailsRouteImport
      parentRoute: typeof TTenantSlugAppRouteRoute
    }
    '/t/$tenantSlug/app/configuracoes': {
      id: '/t/$tenantSlug/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/t/$tenantSlug/app/configuracoes'
      preLoaderRoute: typeof TTenantSlugAppConfiguracoesRouteImport
      parentRoute: typeof TTenantSlugAppRouteRoute
    }
    '/t/$tenantSlug/app/comunicacao': {
      id: '/t/$tenantSlug/app/comunicacao'
      path: '/comunicacao'
      fullPath: '/t/$tenantSlug/app/comunicacao'
      preLoaderRoute: typeof TTenantSlugAppComunicacaoRouteImport
      parentRoute: typeof TTenantSlugAppRouteRoute
    }
    '/t/$tenantSlug/app/chats': {
      id: '/t/$tenantSlug/app/chats'
      path: '/chats'
      fullPath: '/t/$tenantSlug/app/chats'
      preLoaderRoute: typeof TTenantSlugAppChatsRouteImport
      parentRoute: typeof TTenantSlugAppRouteRoute
    }
    '/t/$tenantSlug/app/chamados': {
      id: '/t/$tenantSlug/app/chamados'
      path: '/chamados'
      fullPath: '/t/$tenantSlug/app/chamados'
      preLoaderRoute: typeof TTenantSlugAppChamadosRouteImport
      parentRoute: typeof TTenantSlugAppRouteRoute
    }
    '/t/$tenantSlug/app/agenda': {
      id: '/t/$tenantSlug/app/agenda'
      path: '/agenda'
      fullPath: '/t/$tenantSlug/app/agenda'
      preLoaderRoute: typeof TTenantSlugAppAgendaRouteImport
      parentRoute: typeof TTenantSlugAppRouteRoute
    }
    '/t/$tenantSlug/app/creator': {
      id: '/t/$tenantSlug/app/creator'
      path: '/creator'
      fullPath: '/t/$tenantSlug/app/creator'
      preLoaderRoute: typeof TTenantSlugAppCreatorRouteRouteImport
      parentRoute: typeof TTenantSlugAppRouteRoute
    }
    '/t/$tenantSlug/app/communications': {
      id: '/t/$tenantSlug/app/communications'
      path: '/communications'
      fullPath: '/t/$tenantSlug/app/communications'
      preLoaderRoute: typeof TTenantSlugAppCommunicationsRouteRouteImport
      parentRoute: typeof TTenantSlugAppRouteRoute
    }
    '/t/$tenantSlug/app/funil/': {
      id: '/t/$tenantSlug/app/funil/'
      path: '/funil'
      fullPath: '/t/$tenantSlug/app/funil/'
      preLoaderRoute: typeof TTenantSlugAppFunilIndexRouteImport
      parentRoute: typeof TTenantSlugAppRouteRoute
    }
    '/t/$tenantSlug/app/creator/': {
      id: '/t/$tenantSlug/app/creator/'
      path: '/'
      fullPath: '/t/$tenantSlug/app/creator/'
      preLoaderRoute: typeof TTenantSlugAppCreatorIndexRouteImport
      parentRoute: typeof TTenantSlugAppCreatorRouteRoute
    }
    '/t/$tenantSlug/app/communications/': {
      id: '/t/$tenantSlug/app/communications/'
      path: '/'
      fullPath: '/t/$tenantSlug/app/communications/'
      preLoaderRoute: typeof TTenantSlugAppCommunicationsIndexRouteImport
      parentRoute: typeof TTenantSlugAppCommunicationsRouteRoute
    }
    '/t/$tenantSlug/app/funil/$pipelineId': {
      id: '/t/$tenantSlug/app/funil/$pipelineId'
      path: '/funil/$pipelineId'
      fullPath: '/t/$tenantSlug/app/funil/$pipelineId'
      preLoaderRoute: typeof TTenantSlugAppFunilPipelineIdRouteImport
      parentRoute: typeof TTenantSlugAppRouteRoute
    }
    '/t/$tenantSlug/app/creator/sponsors': {
      id: '/t/$tenantSlug/app/creator/sponsors'
      path: '/sponsors'
      fullPath: '/t/$tenantSlug/app/creator/sponsors'
      preLoaderRoute: typeof TTenantSlugAppCreatorSponsorsRouteImport
      parentRoute: typeof TTenantSlugAppCreatorRouteRoute
    }
    '/t/$tenantSlug/app/creator/campaigns': {
      id: '/t/$tenantSlug/app/creator/campaigns'
      path: '/campaigns'
      fullPath: '/t/$tenantSlug/app/creator/campaigns'
      preLoaderRoute: typeof TTenantSlugAppCreatorCampaignsRouteImport
      parentRoute: typeof TTenantSlugAppCreatorRouteRoute
    }
    '/t/$tenantSlug/app/creator/brands': {
      id: '/t/$tenantSlug/app/creator/brands'
      path: '/brands'
      fullPath: '/t/$tenantSlug/app/creator/brands'
      preLoaderRoute: typeof TTenantSlugAppCreatorBrandsRouteImport
      parentRoute: typeof TTenantSlugAppCreatorRouteRoute
    }
    '/t/$tenantSlug/app/creator/agencies': {
      id: '/t/$tenantSlug/app/creator/agencies'
      path: '/agencies'
      fullPath: '/t/$tenantSlug/app/creator/agencies'
      preLoaderRoute: typeof TTenantSlugAppCreatorAgenciesRouteImport
      parentRoute: typeof TTenantSlugAppCreatorRouteRoute
    }
    '/t/$tenantSlug/app/communications/tickets': {
      id: '/t/$tenantSlug/app/communications/tickets'
      path: '/tickets'
      fullPath: '/t/$tenantSlug/app/communications/tickets'
      preLoaderRoute: typeof TTenantSlugAppCommunicationsTicketsRouteImport
      parentRoute: typeof TTenantSlugAppCommunicationsRouteRoute
    }
    '/t/$tenantSlug/app/communications/settings': {
      id: '/t/$tenantSlug/app/communications/settings'
      path: '/settings'
      fullPath: '/t/$tenantSlug/app/communications/settings'
      preLoaderRoute: typeof TTenantSlugAppCommunicationsSettingsRouteImport
      parentRoute: typeof TTenantSlugAppCommunicationsRouteRoute
    }
    '/t/$tenantSlug/app/communications/reports': {
      id: '/t/$tenantSlug/app/communications/reports'
      path: '/reports'
      fullPath: '/t/$tenantSlug/app/communications/reports'
      preLoaderRoute: typeof TTenantSlugAppCommunicationsReportsRouteImport
      parentRoute: typeof TTenantSlugAppCommunicationsRouteRoute
    }
    '/t/$tenantSlug/app/communications/integrations': {
      id: '/t/$tenantSlug/app/communications/integrations'
      path: '/integrations'
      fullPath: '/t/$tenantSlug/app/communications/integrations'
      preLoaderRoute: typeof TTenantSlugAppCommunicationsIntegrationsRouteImport
      parentRoute: typeof TTenantSlugAppCommunicationsRouteRoute
    }
    '/t/$tenantSlug/app/communications/inbox': {
      id: '/t/$tenantSlug/app/communications/inbox'
      path: '/inbox'
      fullPath: '/t/$tenantSlug/app/communications/inbox'
      preLoaderRoute: typeof TTenantSlugAppCommunicationsInboxRouteImport
      parentRoute: typeof TTenantSlugAppCommunicationsRouteRoute
    }
    '/t/$tenantSlug/app/communications/channels': {
      id: '/t/$tenantSlug/app/communications/channels'
      path: '/channels'
      fullPath: '/t/$tenantSlug/app/communications/channels'
      preLoaderRoute: typeof TTenantSlugAppCommunicationsChannelsRouteImport
      parentRoute: typeof TTenantSlugAppCommunicationsRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminBillingRoute: typeof AdminBillingRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTenantsTenantIdRoute: typeof AdminTenantsTenantIdRoute
  AdminTenantsIndexRoute: typeof AdminTenantsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBillingRoute: AdminBillingRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminTenantsTenantIdRoute: AdminTenantsTenantIdRoute,
  AdminTenantsIndexRoute: AdminTenantsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface TTenantSlugAppCommunicationsRouteRouteChildren {
  TTenantSlugAppCommunicationsChannelsRoute: typeof TTenantSlugAppCommunicationsChannelsRoute
  TTenantSlugAppCommunicationsInboxRoute: typeof TTenantSlugAppCommunicationsInboxRoute
  TTenantSlugAppCommunicationsIntegrationsRoute: typeof TTenantSlugAppCommunicationsIntegrationsRoute
  TTenantSlugAppCommunicationsReportsRoute: typeof TTenantSlugAppCommunicationsReportsRoute
  TTenantSlugAppCommunicationsSettingsRoute: typeof TTenantSlugAppCommunicationsSettingsRoute
  TTenantSlugAppCommunicationsTicketsRoute: typeof TTenantSlugAppCommunicationsTicketsRoute
  TTenantSlugAppCommunicationsIndexRoute: typeof TTenantSlugAppCommunicationsIndexRoute
}

const TTenantSlugAppCommunicationsRouteRouteChildren: TTenantSlugAppCommunicationsRouteRouteChildren =
  {
    TTenantSlugAppCommunicationsChannelsRoute:
      TTenantSlugAppCommunicationsChannelsRoute,
    TTenantSlugAppCommunicationsInboxRoute:
      TTenantSlugAppCommunicationsInboxRoute,
    TTenantSlugAppCommunicationsIntegrationsRoute:
      TTenantSlugAppCommunicationsIntegrationsRoute,
    TTenantSlugAppCommunicationsReportsRoute:
      TTenantSlugAppCommunicationsReportsRoute,
    TTenantSlugAppCommunicationsSettingsRoute:
      TTenantSlugAppCommunicationsSettingsRoute,
    TTenantSlugAppCommunicationsTicketsRoute:
      TTenantSlugAppCommunicationsTicketsRoute,
    TTenantSlugAppCommunicationsIndexRoute:
      TTenantSlugAppCommunicationsIndexRoute,
  }

const TTenantSlugAppCommunicationsRouteRouteWithChildren =
  TTenantSlugAppCommunicationsRouteRoute._addFileChildren(
    TTenantSlugAppCommunicationsRouteRouteChildren,
  )

interface TTenantSlugAppCreatorRouteRouteChildren {
  TTenantSlugAppCreatorAgenciesRoute: typeof TTenantSlugAppCreatorAgenciesRoute
  TTenantSlugAppCreatorBrandsRoute: typeof TTenantSlugAppCreatorBrandsRoute
  TTenantSlugAppCreatorCampaignsRoute: typeof TTenantSlugAppCreatorCampaignsRoute
  TTenantSlugAppCreatorSponsorsRoute: typeof TTenantSlugAppCreatorSponsorsRoute
  TTenantSlugAppCreatorIndexRoute: typeof TTenantSlugAppCreatorIndexRoute
}

const TTenantSlugAppCreatorRouteRouteChildren: TTenantSlugAppCreatorRouteRouteChildren =
  {
    TTenantSlugAppCreatorAgenciesRoute: TTenantSlugAppCreatorAgenciesRoute,
    TTenantSlugAppCreatorBrandsRoute: TTenantSlugAppCreatorBrandsRoute,
    TTenantSlugAppCreatorCampaignsRoute: TTenantSlugAppCreatorCampaignsRoute,
    TTenantSlugAppCreatorSponsorsRoute: TTenantSlugAppCreatorSponsorsRoute,
    TTenantSlugAppCreatorIndexRoute: TTenantSlugAppCreatorIndexRoute,
  }

const TTenantSlugAppCreatorRouteRouteWithChildren =
  TTenantSlugAppCreatorRouteRoute._addFileChildren(
    TTenantSlugAppCreatorRouteRouteChildren,
  )

interface TTenantSlugAppRouteRouteChildren {
  TTenantSlugAppCommunicationsRouteRoute: typeof TTenantSlugAppCommunicationsRouteRouteWithChildren
  TTenantSlugAppCreatorRouteRoute: typeof TTenantSlugAppCreatorRouteRouteWithChildren
  TTenantSlugAppAgendaRoute: typeof TTenantSlugAppAgendaRoute
  TTenantSlugAppChamadosRoute: typeof TTenantSlugAppChamadosRoute
  TTenantSlugAppChatsRoute: typeof TTenantSlugAppChatsRoute
  TTenantSlugAppComunicacaoRoute: typeof TTenantSlugAppComunicacaoRoute
  TTenantSlugAppConfiguracoesRoute: typeof TTenantSlugAppConfiguracoesRoute
  TTenantSlugAppEmailsRoute: typeof TTenantSlugAppEmailsRoute
  TTenantSlugAppFaturamentoRoute: typeof TTenantSlugAppFaturamentoRoute
  TTenantSlugAppPainelRoute: typeof TTenantSlugAppPainelRoute
  TTenantSlugAppPropostasRoute: typeof TTenantSlugAppPropostasRoute
  TTenantSlugAppIndexRoute: typeof TTenantSlugAppIndexRoute
  TTenantSlugAppFunilPipelineIdRoute: typeof TTenantSlugAppFunilPipelineIdRoute
  TTenantSlugAppFunilIndexRoute: typeof TTenantSlugAppFunilIndexRoute
}

const TTenantSlugAppRouteRouteChildren: TTenantSlugAppRouteRouteChildren = {
  TTenantSlugAppCommunicationsRouteRoute:
    TTenantSlugAppCommunicationsRouteRouteWithChildren,
  TTenantSlugAppCreatorRouteRoute: TTenantSlugAppCreatorRouteRouteWithChildren,
  TTenantSlugAppAgendaRoute: TTenantSlugAppAgendaRoute,
  TTenantSlugAppChamadosRoute: TTenantSlugAppChamadosRoute,
  TTenantSlugAppChatsRoute: TTenantSlugAppChatsRoute,
  TTenantSlugAppComunicacaoRoute: TTenantSlugAppComunicacaoRoute,
  TTenantSlugAppConfiguracoesRoute: TTenantSlugAppConfiguracoesRoute,
  TTenantSlugAppEmailsRoute: TTenantSlugAppEmailsRoute,
  TTenantSlugAppFaturamentoRoute: TTenantSlugAppFaturamentoRoute,
  TTenantSlugAppPainelRoute: TTenantSlugAppPainelRoute,
  TTenantSlugAppPropostasRoute: TTenantSlugAppPropostasRoute,
  TTenantSlugAppIndexRoute: TTenantSlugAppIndexRoute,
  TTenantSlugAppFunilPipelineIdRoute: TTenantSlugAppFunilPipelineIdRoute,
  TTenantSlugAppFunilIndexRoute: TTenantSlugAppFunilIndexRoute,
}

const TTenantSlugAppRouteRouteWithChildren =
  TTenantSlugAppRouteRoute._addFileChildren(TTenantSlugAppRouteRouteChildren)

interface TTenantSlugPortalRouteRouteChildren {
  TTenantSlugPortalChamadosRoute: typeof TTenantSlugPortalChamadosRoute
  TTenantSlugPortalFaturamentoRoute: typeof TTenantSlugPortalFaturamentoRoute
  TTenantSlugPortalProjetosRoute: typeof TTenantSlugPortalProjetosRoute
  TTenantSlugPortalPropostasRoute: typeof TTenantSlugPortalPropostasRoute
  TTenantSlugPortalIndexRoute: typeof TTenantSlugPortalIndexRoute
}

const TTenantSlugPortalRouteRouteChildren: TTenantSlugPortalRouteRouteChildren =
  {
    TTenantSlugPortalChamadosRoute: TTenantSlugPortalChamadosRoute,
    TTenantSlugPortalFaturamentoRoute: TTenantSlugPortalFaturamentoRoute,
    TTenantSlugPortalProjetosRoute: TTenantSlugPortalProjetosRoute,
    TTenantSlugPortalPropostasRoute: TTenantSlugPortalPropostasRoute,
    TTenantSlugPortalIndexRoute: TTenantSlugPortalIndexRoute,
  }

const TTenantSlugPortalRouteRouteWithChildren =
  TTenantSlugPortalRouteRoute._addFileChildren(
    TTenantSlugPortalRouteRouteChildren,
  )

interface TTenantSlugRouteRouteChildren {
  TTenantSlugAppRouteRoute: typeof TTenantSlugAppRouteRouteWithChildren
  TTenantSlugPortalRouteRoute: typeof TTenantSlugPortalRouteRouteWithChildren
}

const TTenantSlugRouteRouteChildren: TTenantSlugRouteRouteChildren = {
  TTenantSlugAppRouteRoute: TTenantSlugAppRouteRouteWithChildren,
  TTenantSlugPortalRouteRoute: TTenantSlugPortalRouteRouteWithChildren,
}

const TTenantSlugRouteRouteWithChildren =
  TTenantSlugRouteRoute._addFileChildren(TTenantSlugRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AgendaRoute: AgendaRoute,
  ChatsRoute: ChatsRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EmailsRoute: EmailsRoute,
  FunilRoute: FunilRoute,
  LoginRoute: LoginRoute,
  PainelRoute: PainelRoute,
  PropostasRoute: PropostasRoute,
  TTenantSlugRouteRoute: TTenantSlugRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
